# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = true

# Set a format for the prompt
format = """
[╭─](bold green)$directory$git_branch$git_status
[╰─](bold green)$character"""

# Timeout for commands executed, default is 10 seconds
command_timeout = 1000

[directory]
style = "bold blue"
truncation_length = 5
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold red"
conflicted = "Conflicted "
ahead = "Ahead "
behind = "Behind "
diverged = "Diverged "
untracked = "? "
stashed = "stashed "
modified = "Modified "
staged = "+ "
renamed = "Renamed "
deleted = "Deleted "
format = "[$all_status]($style)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[V](bold green)"
